---
name: garden-runc

# replace with bosh status --uuid
director_uuid: <%= `bosh target lite > /dev/null 2>&1 && bosh status --uuid` %>

releases:
  - name: garden-runc
    version: latest
  - name: grootfs
    version: 0.24.0
    url: http://bosh.io/d/github.com/cloudfoundry/grootfs-release?v=0.24.0
    sha1: b342db5da3a7bd7bb2e81c2f6456d75cf38e9e0c

jobs:
  - name: garden
    instances: 1
    templates:
      - name: grootfs
        release: grootfs
      - name: garden
        release: garden-runc
    resource_pool: garden
    networks:
      - name: garden
    properties:
      garden:
        default_container_rootfs: docker:///busybox:buildroot-2014.02
        graph_cleanup_threshold_in_mb: 1024
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        debug_listen_address: 0.0.0.0:17013
        log_level: debug
        network_plugin: /bin/true
        image_plugin: /var/vcap/packages/grootfs/bin/grootfs
        image_plugin_extra_args: ["--config", "/var/vcap/jobs/grootfs/config/grootfs_config.yml"]
        experimental_rootless_mode: true
      grootfs:
        store_size_bytes: 524288000
        driver: btrfs
        json_output: true

networks:
  - name: garden
    subnets:
      - range: 10.244.16.4/30
        reserved: [10.244.16.5]
        static: []
        cloud_properties:
          name: random
      - range: 10.244.16.8/30
        reserved: [10.244.16.9]
        static: []
        cloud_properties:
          name: random
      - range: 10.244.16.12/30
        reserved: [10.244.16.13]
        static: []
        cloud_properties:
          name: random
      - range: 10.244.16.16/30
        reserved: [10.244.16.17]
        static: []
        cloud_properties:
          name: random
      - range: 10.244.16.20/30
        reserved: [10.244.16.21]
        static: []
        cloud_properties:
          name: random

resource_pools:
  # not much point in having more than one resource pool, since it's all
  # in one VM with the same hardware anyway
  - name: garden
    network: garden
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      name: random

compilation:
  workers: 3
  network: garden
  cloud_properties:
    name: random

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-240000
  update_watch_time: 1000-240000
