---
dev_name: paasta-influxdb-grafana
latest_release_filename: "/home/csupshin/workspace/paasta/paasta-git/Monitoring/releases/paasta-influxdb-grafana-3.0/dev_releases/paasta-influxdb-grafana/paasta-influxdb-grafana-0+dev.1.yml"
