compilation:
  cloud_properties:
    name: default
  network: monitoring-alarm-server-net
  reuse_compilation_vms: true
  workers: 1
director_uuid: 28539132-6d43-4e1b-bf40-f2ce032ee9f8
jobs:
- cloud_properties:
    name: default
  instances: 1
  memory_mb: 2048
  name: alarm_server_z1
  networks:
  - name: monitoring-alarm-server-net
    static_ips: 10.244.30.40
  properties: {}
  resource_pool: monitoring-alarm-server
  templates:
  - name: alarm_server
    release: monitoring-alarm-server
  update:
    max_in_flight: 1
    serial: false
meta:
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
name: monitoring-alarm-server
networks:
- name: monitoring-alarm-server-net
  subnets:
  - cloud_properties:
      name: monitoring-alarm-server-net
    gateway: 10.244.30.1
    range: 10.244.30.0/24
    static:
    - 10.244.30.40 - 10.244.30.60
properties:
  syslog_daemon_config:
    address: null
    port: null
  alarm_server:
    listen_addr: 0.0.0.0:9999
    log_level: debug
    bosh:
      url: https://52.207.82.208:25555
      user: admin
      pass: admin
    manager: Administrator
    manager_email: admin@openpaas.com
    sender: alarmservice.monitoring@gmail.com
    sender_password: zmfhtpsxm12
    threshold:
      cpu: 70
      memory: 70
      disk: 70
releases:
- name: monitoring-alarm-server
  version: latest
- name: cf
  version: latest
resource_pools:
- cloud_properties:
    name: default
  name: monitoring-alarm-server
  network: monitoring-alarm-server-net
  size: 1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 30000-100000
  max_errors: 1
  max_in_flight: 1
  update_watch_time: 30000-100000

