---
dev_name: paasta-influxdb-grafana
latest_release_filename: "/home/ihocho/workspace/openpaas-monitoring-v247/paasta-influxdb-grafana-2.0/dev_releases/paasta-influxdb-grafana/paasta-influxdb-grafana-2.0.yml"
