compilation:
  cloud_properties:
    availability_zone: us-east-1d
    instance_type: c3.large
  network: metrics-collector-net
  reuse_compilation_vms: true
  workers: 1
director_uuid: <%= `bosh status --uuid` %>

jobs:
- instances: 2
  name: metrics_collector_z1
  networks:
  - name: metrics-collector-net
    static_ips: 
    - 10.10.5.101
    - 10.10.5.102
  properties: {}
  resource_pool: metrics-collector
  templates:
  - name: metrics_collector
    release: metrics-collector
  update:
    max_in_flight: 1
    serial: true

meta:
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
name: metrics-collector
networks:
- name: metrics-collector-net
  subnets:
  - cloud_properties:
      security_groups:
      - cf-diego-stack2-InternalSecurityGroup-11HQXLKO7IEWL
      subnet: subnet-f4b255d9
    dns:
    - 52.71.253.54
    - 10.10.0.2
    gateway: 10.10.5.1
    range: 10.10.5.0/24
    reserved:
    - 10.10.5.2 - 10.10.5.70
    static:
    - 10.10.5.101 - 10.10.5.110
  type: manual

properties:
  syslog_daemon_config:
    address: null
    port: null
  metrics_collector:
    uaaUrl: https://uaa.v2.monitxpert.com
    clientId: cf
    clientPass: null
    influx:
      url: 10.10.18.51:8089
      database: cf_metric_db
      cf_measurement: cf_metrics
      cf_process_measurement : cf_process_metrics
    dopplerUrl:
    - wss://doppler.v2.monitxpert.com:4443
    log_level: debug
releases:
- name: metrics-collector
  version: latest
resource_pools:
- cloud_properties:
    availability_zone: us-east-1d
    instance_type: m3.medium
  name: metrics-collector
  network: metrics-collector-net 
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 30000-100000
  max_errors: 1
  max_in_flight: 1
  update_watch_time: 30000-100000

