compilation:
  cloud_properties:
    name: default
  network: metrics-collector-net
  reuse_compilation_vms: true
  workers: 1
director_uuid: <%= `bosh status --uuid` %>
jobs:
- cloud_properties:
    name: default
  instances: 1
  memory_mb: 2048
  name: metrics_collector_z1
  networks:
  - name: metrics-collector-net
    static_ips: 10.244.30.2
  properties: {}
  resource_pool: metrics-collector
  templates:
  - name: metrics_collector
    release: metrics-collector
  update:
    max_in_flight: 1
    serial: false
meta:
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
name: metrics-collector
networks:
- name: metrics-collector-net
  subnets:
  - cloud_properties:
      name: metrics-collector-net
    gateway: 10.244.30.1
    range: 10.244.30.0/24
    static:
    - 10.244.30.2 - 10.244.30.12
properties:
  syslog_daemon_config:
    address: null
    port: null
  metrics_collector:
    uaaUrl: http://uaa.bosh-lite.com
    clientId: cf
    clientPass: null
    influx:
      url: 192.168.4.16:8089
      database: cf_metric_db
      cf_measurement: cf_metrics
      cf_process_measurement : cf_process_metrics
    dopplerUrl: 
    - wss://doppler.bosh-lite.com:443
    log_level: debug
releases:
- name: metrics-collector
  version: latest
resource_pools:
- cloud_properties:
    name: default
  name: metrics-collector
  network: metrics-collector-net
  size: 1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 30000-100000
  max_errors: 1
  max_in_flight: 1
  update_watch_time: 30000-100000

