---
dev_name: paasta-metrics-collector
latest_release_filename: "/home/ihocho/workspace/openpaas-monitoring-v247/paasta-metrics-collector-2.0/dev_releases/paasta-metrics-collector/paasta-metrics-collector-2.0.yml"
